[project]
name = "test-mcp"
version = "0.1.0"
description = "Real Time stock assistant"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "httpx>=0.28.1",
    "mcp[cli]>=1.6.0",
    "yfinance"
]